[account]
name = "Client"

[clusters]
points = [
    "cassandra-1",
    "cassandra-2",
    "cassandra-3",
]

[network.client]
ip = "127.0.0.1"
port = 8080

[network.server]
ip = "0.0.0.0"
port = 8080
