[account]
name = "Client"

[cassandra]
points = [
    # "cassandra1",
    # "cassandra2",
    # "cassandra3",
    "172.18.0.2",
    "172.18.0.3",
    "172.18.0.4",
]
keyspace = "medicines"
repl_factor = 3

[network.client]
ip = "127.0.0.1"
port = 8080

[network.server]
ip = "0.0.0.0"
port = 8080
