from cassandra.cqlengine import columns
from cassandra.cqlengine.models import Model


class Medicine(Model):
    id = columns.Integer(primary_key=True)
    name = columns.Text()
    substitute0 = columns.Text()
    substitute1 = columns.Text()
    substitute2 = columns.Text()
    substitute3 = columns.Text()
    substitute4 = columns.Text()
    side_effect0 = columns.Text()
    side_effect1 = columns.Text()
    side_effect2 = columns.Text()
    side_effect3 = columns.Text()
    side_effect4 = columns.Text()
    side_effect5 = columns.Text()
    side_effect6 = columns.Text()
    side_effect7 = columns.Text()
    side_effect8 = columns.Text()
    side_effect9 = columns.Text()
    side_effect10 = columns.Text()
    side_effect11 = columns.Text()
    side_effect12 = columns.Text()
    side_effect13 = columns.Text()
    side_effect14 = columns.Text()
    side_effect15 = columns.Text()
    side_effect16 = columns.Text()
    side_effect17 = columns.Text()
    side_effect18 = columns.Text()
    side_effect19 = columns.Text()
    side_effect20 = columns.Text()
    side_effect21 = columns.Text()
    side_effect22 = columns.Text()
    side_effect23 = columns.Text()
    side_effect24 = columns.Text()
    side_effect25 = columns.Text()
    side_effect26 = columns.Text()
    side_effect27 = columns.Text()
    side_effect28 = columns.Text()
    side_effect29 = columns.Text()
    side_effect30 = columns.Text()
    side_effect31 = columns.Text()
    side_effect32 = columns.Text()
    side_effect33 = columns.Text()
    side_effect34 = columns.Text()
    side_effect35 = columns.Text()
    side_effect36 = columns.Text()
    side_effect37 = columns.Text()
    side_effect38 = columns.Text()
    side_effect39 = columns.Text()
    side_effect40 = columns.Text()
    side_effect41 = columns.Text()
    use0 = columns.Text()
    use1 = columns.Text()
    use2 = columns.Text()
    use3 = columns.Text()
    use4 = columns.Text()
    chemical_class = columns.Text()
    habit_forming = columns.Text()
    therapeutic_class = columns.Text()
    action_class = columns.Text()
    count = columns.Integer()


class Reservation(Model):
    id = columns.Integer(primary_key=True)
    account_name = columns.Text()
    medicine = columns.Text()
    count = columns.Text()
